### ISSUE TITLE
Mozilla Addons warning - solution, move R icon to "awesome bar"?

### ISSUE THREAD

**Issue by sjschultze** [freelawproject/recap-firefox#7]
Harlan is getting this crap when he submits to addons.mozilla.org. It doesn't block us from submitting, but it probably means that we need to move the R icon from the addons bar to somewhere else (like the annoyingly named "[Awesome Bar](http://support.mozilla.org/en-US/kb/awesome-bar-find-your-bookmarks-history-and-tabs)", which is where all extension icons seem to be migrating).

```
Menu item has been moved
Warning: Your add-on has an overlay that uses the insertbefore or insertafter attribute pointing to menuitems that have been moved to a different menu item. Your overlay items may appear in unexpected locations because of this. See https://bugzilla.mozilla.org/show_bug.cgi?id=653221 for more information.
    content/firefoxOverlay.xul
    41
    42
    43
    <menupopup id="menu_ToolsPopup">
      <menuitem label="RECAP Preferences..." oncommand="recap.openPrefs()" image="chrome://recap/skin/recap-icon-32.png" insertafter="javascriptCo ...
    </menupopup>
```

**Comment by mlissner** [comment]
I believe this too is fixed in the version that's about to come out. Look for an improved icon/menu situation when it upgrades!
